### ISSUE TITLE
Errors on attempting to analyze a file

### ISSUE THREAD

**Issue by geeksailor** [digitalsleuth/peepdf-3#1]
@digitalsleuth As you requested, I'm opening a ticket for the issue I found with peepdf.
I can run `peepdf` by itself with no issue and get the help option. But when I attempt to run it on a pdf using `peepdf <file.pdf>` The following is outputted to my terminal:
>Please don't forget to report the errors found:
	- Send the file "/home/remnux/peepdf_errors.txt" to the author (mailto:peepdfREMOVETHIS@eternal-todo.com)
	- And/Or creating an issue on the project webpage (https://github.com/jesparza/peepdf/issues)

Executing `cat peepdf_errors.txt` outputs the following from the file:
>Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/peepdf/main.py", line 553, in main
    ret, pdf = pdfParser.parse(
  File "/usr/local/lib/python3.8/dist-packages/peepdf/PDFCore.py", line 7681, in parse
    ret = body.updateObjects()
  File "/usr/local/lib/python3.8/dist-packages/peepdf/PDFCore.py", line 4571, in updateObjects
    object.resolveReferences()
  File "/usr/local/lib/python3.8/dist-packages/peepdf/PDFCore.py", line 3523, in resolveReferences
    ret = PDFParser.readObject(objectsSection[offset:])
TypeError: readObject() missing 1 required positional argument: 'content'

I'm attempting to troubleshooting this error on my own to see if I can help figure out a solution but my python-fu is weak and I'm betting you will figure it out well before I do. Anyways hope you are able to figure out what the issue is.
Thanks!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , can you confirm that the file you attempted this on is in-fact a PDF file by running `file <file.pdf>`? Additionally, if you're able to provide the pdf file, please let me know as well.

**Comment by geeksailor** [comment]
Also it appears that the error output overrides the error file every time rather than appends so any old issues get lost. Another small thing but no time stamps in the file for when that error written so you have to look at the file timestamp itself to see when it was outputted to it. Again small stuff but things maybe for consideration for future releases.

**Comment by digitalsleuth** [comment]
I am aware of those issues, and am working on them for an upcoming release with files named for the date-time of the error / issue, but thanks for making note of them.

**Comment by geeksailor** [comment]
@digitalsleuth file uploaded. I'm not sure if it is malicious or not, so I zipped it up and password protected it. Password is infected
[pdf.zip](https://github.com/digitalsleuth/peepdf-3/files/12651783/pdf.zip)

**Comment by digitalsleuth** [comment]
@geeksailor This error should now be fixed as version 1.0.8. I'll be pushing a pip package eventually in the next few days so it can be installed that way, however in order to get the latest version, you can run:
```bash
sudo python3 -m pip install --upgrade git+https://github.com/digitalsleuth/peepdf-3.git
```

**Comment by geeksailor** [comment]
Awesome! Thanks for the quick fix mate! I'll pull it now.
Cheers!

**Comment by geeksailor** [comment]
@digitalsleuth 
Tried running it on that file again and got the following error:
>[!] Error: An error has occurred while parsing an indirect object

**Comment by geeksailor** [comment]
Happens on some files but not others. Can't really tell what the differences are and what is causing it.

**Comment by digitalsleuth** [comment]
The "indirect object" error happens occasionally with some PDF's. You can safely ignore this error by using the `-f` option on the file.

**Comment by digitalsleuth** [comment]
Hi @geeksailor , the indirect object error has been addressed, as have the error logs being overwritten and poorly named. These are addressed in v1.0.9.

Cheers!

**Comment by geeksailor** [comment]
@digitalsleuth Thanks for the fix! Just pulled it and I am testing it out now. 
Just out of curiosity does the logs still write locally or do they output to a certain location now?

**Comment by geeksailor** [comment]
Seems to work for me now. However I have a few test files I'm probing and one of them I just discovered has encryption. When I tried to run peepdf on it, it gave me the error
>[!] Decryption error: Algorithm revision not supported

But still seemed to run fine otherwise
