### ISSUE TITLE
Interactive Mode Error

### ISSUE THREAD

**Issue by geeksailor** [digitalsleuth/peepdf-3#16]
@digitalsleuth Got another one for ya. Went into interactive mode on a pdf and ran the filters command and came back with:
> PPDF> filters

>[!] Error: The command line arguments have not been parsed successfully

Not sure if this is because I ran the command by itself and confused it but thought I would throw it your way to check out.
Cheers!

**Comment by digitalsleuth** [comment]
This is actually expected behaviour as well, since the `filters` command requires an object ID in order to process. Without an argument / object ID to perform an action on, the command "safely" errors out, and presents the usage menu to prompt for more info:

```bash
PPDF> filters

[!] Error: The command line arguments have not been parsed successfully


Usage: filters $object_id [$version] [$filter1 [$filter2 ...]]
Shows the filters found in the stream object or set the filters in the object (first filter is used first). The valid values for filters are the following:
        none: No filters
        asciihex,ahx: /ASCIIHexDecode
        ascii85,a85: /ASCII85Decode (Not implemented)
        lzw: /LZWDecode
        flatedecode,fl: /FlateDecode
        runlength,rl: /RunLengthDecode (Not implemented)
        ccittfax,ccf: /CCITTFaxDecode (Not implemented)
        jbig2: /JBIG2Decode (Not implemented)
        dct: /DCTDecode (Not implemented)
        jpx: /JPXDecode (Not implemented)
```

```bash
PPDF> streams

Version 0: Streams (14): [10, 11, 12, 13, 14, 15, 18, 19, 22, 23, 26, 27, 30, 32]

PPDF> filters 10

/FlateDecode
```

**Comment by geeksailor** [comment]
OK so it is what I thought it might be, but I wanted to be sure. Thanks!
Cheers!
