### ISSUE TITLE
String Pattern Error

### ISSUE THREAD

**Issue by geeksailor** [digitalsleuth/peepdf-3#2]
Hola @digitalsleuth!
Been a bit since I threw something your way. So I think my previous issue with Peepdf has been resolved. I think that somehow Peepdf (the original one) somehow got reinstalled somewhere along the way which overrode links for Peepdf and my system was trying to run the original rather than Peepdf-3. So I had to remove both and reinstall Peepdf3 in order to restore all the proper links. To test it, I decided to run it on a few (4) test pdf's I just picked up from my local email spam. On one of the pdfs I ended up with the following error:
>Traceback (most recent call last):
  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/main.py", line 552, in main
    ret, pdf = pdfParser.parse(
  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/PDFCore.py", line 7681, in parse
    ret = body.updateObjects()
  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/PDFCore.py", line 4572, in updateObjects
    object.resolveReferences()
  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/PDFCore.py", line 2773, in resolveReferences
    refs = re.findall("(\d{1,5}\s{1,3}\d{1,5}\s{1,3}R)", self.decodedStream)
  File "/usr/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

Figured I would throw it back your way to take a peek at and see if it was worth trying to fix.
Cheers!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , glad you reached out! Can you provide a few basics about the PDF in question:
- file size
- output of `file <pdf_file>` where <pdf_file> is the file in question
- Is the PDF a complete or partial PDF
- Does it contain encryption

Cheers!

**Comment by geeksailor** [comment]
@digitalsleuth 
the files size is 38020 (38k). File reports it as a PDF document, version 1.5. As for complete or partial and encryption it is hard to tell. PDFID came back negative for having encryption. `qpdf --show-encryption` came back as negative as well. Other programs seem to be running ok against it. pdf-parser.py, pdftk, pdfcop ran against it and reported back no problem. I have attached the file here for you in case you want to play around with it. password is `infected`.
[pdf.zip](https://github.com/digitalsleuth/peepdf-3/files/13392476/pdf.zip)

Cheers!

**Comment by geeksailor** [comment]
@digitalsleuth got another one from a different pdf. Went into interactive mode on this different pdf and tried to run a filter `filters ## fl` on an image and came back with 
> [!] Error: Exception not handled using the interactive console - please report it to the author.

After I quit it spat out an error file that had the following:
>Traceback (most recent call last):
  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/main.py", line 864, in main
    console.cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/PDFConsole.py", line 1372, in do_filters
    validFilters = filter2RealFilterDict.keys() + ["none"]
TypeError: unsupported operand type(s) for +: 'dict_keys' and 'list'

EDIT: Tried this on yet another different pdf same process and same error as well. This one might be a program wide flaw that occurs on all pdf's rather than a one off bug caused by just one pdf. I think this might go back to line 91 in PDFConsole.py but I'm not entirely sure. My python-fu isn't great and luck with trying to combine dictionaries, lists, tuples together has never really been that good. I'm sure you'll figure it out though.
Cheers!

**Comment by geeksailor** [comment]
After some Googling, I think the first issue has something to do with converting certain strings to bytes (I guess that is also a given by the error output).  I tried adding a b to line 2772 so it reads it as bytes rather than a string like so:
>refs = re.findall(b"(\d{1,5}\s{1,3}\d{1,5}\s{1,3}R)", self.decodedStream)

It seems to be past that now and is finding a similar error listed below on JSAnalysis.py that I am stuck on trying to see if I can find a fix. 
>   File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/JSAnalysis.py", line 214, in isJavascript
    if re.findall(reJSscript, content, re.DOTALL | re.IGNORECASE):
  File "/usr/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

I see that line refers to reJSscript which I found on line 57, so I tried adding a b to that line as well so it becomes:
>reJSscript = b'<script[^>]*?contentType\s*?=\s*?[\'"]application/x-javascript[\'"][^>]*?>(.*?)</script>'

Then the error kicks on down the road a few lines to give the error:
>  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/JSAnalysis.py", line 218, in isJavascript
    if (ord(char) < 32 and char not in ["\n", "\r", "\t", "\f", "\x00"]) or ord(
TypeError: ord() expected string of length 1, but int found

Not sure if this helps give any insight so far on trying to figure this issue out. But that's as far as I've gotten so far. About to break for lunch for a bit then might kick it around for a little bit longer to see what else I can figure out.
Cheers!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , you've done quite a bit of research on this! I'm just getting back to my PC and will take a look at these this weekend. Cheers!

**Comment by geeksailor** [comment]
After some Googling, I think the first issue has something to do with converting certain strings to bytes (I guess that is also a given by the error output).  I tried adding a b to line 2772 so it reads it as bytes rather than a string like so:
>refs = re.findall(b"(\d{1,5}\s{1,3}\d{1,5}\s{1,3}R)", self.decodedStream)

It seems to be past that now and is finding a similar error listed below on JSAnalysis.py that I am stuck on trying to see if I can find a fix. 
>   File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/JSAnalysis.py", line 214, in isJavascript
    if re.findall(reJSscript, content, re.DOTALL | re.IGNORECASE):
  File "/usr/lib/python3.8/re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: cannot use a string pattern on a bytes-like object

I see that line refers to reJSscript which I found on line 57, so I tried adding a b to that line as well so it becomes:
>reJSscript = b'<script[^>]*?contentType\s*?=\s*?[\'"]application/x-javascript[\'"][^>]*?>(.*?)</script>'

Then the error kicks on down the road a few lines to give the error:
>  File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/JSAnalysis.py", line 218, in isJavascript
    if (ord(char) < 32 and char not in ["\n", "\r", "\t", "\f", "\x00"]) or ord(
TypeError: ord() expected string of length 1, but int found

Not sure if this helps give any insight so far on trying to figure this issue out. But that's as far as I've gotten so far. About to break for lunch for a bit then might kick it around for a little bit longer to see what else I can figure out.
Cheers!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , I've got an idea how to attach this issue, but it's going to take a little bit of time on my end. I'll set some time aside this week and weekend to test and resolve it.

Cheers!

**Comment by digitalsleuth** [comment]
> @digitalsleuth got another one from a different pdf. Went into interactive mode on this different pdf and tried to run a filter `filters ## fl` on an image and came back with
> 
> > [!] Error: Exception not handled using the interactive console - please report it to the author.
> 
> After I quit it spat out an error file that had the following:
> 
> > Traceback (most recent call last):
> > File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/main.py", line 864, in main
> > console.cmdloop()
> > File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
> > stop = self.onecmd(line)
> > File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
> > return func(arg)
> > File "/home/remnux/.local/lib/python3.8/site-packages/peepdf/PDFConsole.py", line 1372, in do_filters
> > validFilters = filter2RealFilterDict.keys() + ["none"]
> > TypeError: unsupported operand type(s) for +: 'dict_keys' and 'list'
> 
> EDIT: Tried this on yet another different pdf same process and same error as well. This one might be a program wide flaw that occurs on all pdf's rather than a one off bug caused by just one pdf. I think this might go back to line 91 in PDFConsole.py but I'm not entirely sure. My python-fu isn't great and luck with trying to combine dictionaries, lists, tuples together has never really been that good. I'm sure you'll figure it out though.
> 
> EDIT 2: THINK I FIXED THE SECOND PART. Easy fix too after a little googling. Just need to change line 1372 from
> 
> > validFilters = filter2RealFilterDict.keys() + ["none"]
> 
> to
> 
> > validFilters = list(filter2RealFilterDict) + ["none"]
> 
> Cheers!

I've got this issue fixed now, still working on the bytes issue. I can see the problem, just working on a practical solution :)

**Comment by geeksailor** [comment]
@digitalsleuth Great! Glad to hear you are making headway with this issue!

**Comment by digitalsleuth** [comment]
@geeksailor Before I generate a full pip package for this, I wanted to give you a heads up that this should be fixed, and see if you can confirm by installing the new version directly from github:
```bash
sudo python3 -m pip install --upgrade git+https://github.com/digitalsleuth/peepdf-3.git
```
It's possible you might need quotes, but you shouldn't. 

Cheers!

**Comment by geeksailor** [comment]
@digitalsleuth Just pulled it! I'll give it a test the new few days and see if I hit any errors but so far it looks clean from straight out the gate.
Cheers!

**Comment by digitalsleuth** [comment]
@geeksailor Just an FYI, I'm prepared to release an updated version 2 which has a lot more features and fixes, as [listed here](https://github.com/digitalsleuth/peepdf-3/blob/develop/CHANGELOG.md#peepdf-200-2023-12-11).

In the next 24 hours I'll create the pip package and send out a new release. Let me know if this fixes the issues you've come across!

**Comment by geeksailor** [comment]
@digitalsleuth great! I look forward to trying the new release when it drops!

**Comment by digitalsleuth** [comment]
Dropped it last night actually. I've got some more things planned for it in the long run, so there should be regular updates as well.

Enjoy!

**Comment by digitalsleuth** [comment]
Hi @geeksailor , just following up on this with you. Did this resolve your issue?

**Comment by digitalsleuth** [comment]
Hi @geeksailor , after much testing, I can confirm that this issue should no longer appear with any of your PDF's. However, if a new error occurs, please feel free to open a new issue here.

Cheers!

**Comment by geeksailor** [comment]
@digitalsleuth Hey sorry about the delayed response buddy. Been off on an long holiday vacation and I haven't really checking Github or email for messages. I think it did fix it but I also didn't really get to test it much before I went on vacation. I'll give it some some stress testing though when I get back and have some time to give it a go! Thank you though for the the update to the program and follow up on it!
Cheers!
