### ISSUE TITLE
Python3 Type error when parsing an encrypted PDF

### ISSUE THREAD

**Issue by yogevyuval** [digitalsleuth/peepdf-3#5]
The error is:
```
/usr/local/lib/python3.11/site-packages/peepdf/PDFCore.py in parse(self, fileName, forceMode, looseMode, manualAnalysis)
   7754             pdfFile.addTrailer([trailer, streamTrailer])
   7755         if pdfFile.isEncrypted() and pdfFile.getEncryptDict() is not None:
-> 7756             ret = pdfFile.decrypt()
   7757             if ret[0] == -1:
   7758                 pdfFile.addError(ret[1])

/usr/local/lib/python3.11/site-packages/peepdf/PDFCore.py in decrypt(self, password)
   5812                     else:
   5813                         return (-1, errorMessage)
-> 5814             if isUserPass(password, computedUserPass, dictU, revision):
   5815                 passType = "USER"
   5816             elif isOwnerPass(

/usr/local/lib/python3.11/site-packages/peepdf/PDFCrypto.py in isUserPass(password, computedUserPass, dictU, revision)
    277         print(password)
    278         print(vSalt)
--> 279         inputHash = hashlib.sha256(password + vSalt).digest()
    280         if inputHash == dictU[:32]:
    281             return True

TypeError: can't concat str to bytes
```

Where password is b''

**Comment by digitalsleuth** [comment]
Thanks for bringing this to my attention. As soon as I get back to my computer I'll take a look at it.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @yogevyuval , I've pinpointed the error(s) and have fixed them up. Doing some more testing tonight and will merge tomorrow if testing goes well.

Cheers!

**Comment by digitalsleuth** [comment]
Hi @yogevyuval , I've fixed the errors and decryption should work fine now. I've released version 2.1.0 which contains the fixes. Let me know how it goes.

Cheers!

**Comment by yogevyuval** [comment]
@digitalsleuth Thanks for the quick turnaround!
I see the error is fixed, however a new error has popped up now:


```
    'NoneType' object has no attribute 'getTrailerId'

        stats = pdf.getStats()
        ^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/peepdf/PDFCore.py", line 66
    69, in getStats
        streamTrailerId = streamTrailer.getTrailerId()
```

**Comment by digitalsleuth** [comment]
Hi @yogevyuval , I noticed that error immediately after releasing 2.1.0, and it's fixed in 2.2.0. Try upgrading and let me know how that goes.

Cheers!

**Comment by yogevyuval** [comment]
> Hi @yogevyuval , I noticed that error immediately after releasing 2.1.0, and it's fixed in 2.2.0. Try upgrading and let me know how that goes.
> 
> Cheers!

Hi @digitalsleuth! the errors are gone, but there is another regression from 2.2.0 with jacascript code detection in the PDF.
I have a simple PDF with a simple js code that was detected with `pdf.getJavascriptCode()` and returned:
```
[['function showAlert() {\r\n    alert("Alert from JS file");\r\n}']]
```

But with version 2.2.0 it returns an empty list.

**Comment by digitalsleuth** [comment]
@yogevyuval , I'm pretty sure I didn't change anything which would have caused that issue, but I'll look into it. Are you able to provide the sample you used for testing?

**Comment by yogevyuval** [comment]
Here it is, the result is different between 2.0.0. and 2.2.0
[js_injected_test.pdf](https://github.com/digitalsleuth/peepdf-3/files/13799955/js_injected_test.pdf)

**Comment by digitalsleuth** [comment]
@yogevyuval What commands did you run to get that output? I'm looking now and want to try to duplicate your process to see where the error lies.

**Comment by yogevyuval** [comment]
> @yogevyuval What commands did you run to get that output? I'm looking now and want to try to duplicate your process to see where the error lies.

@digitalsleuth 
```
pdf_parser = PDFParser()
_, pdf = pdf_parser.parse(input_path, forceMode=True, looseMode=True, manualAnalysis=False)
js_code = pdf.getJavascriptCode()
print(js_code)
```

**Comment by digitalsleuth** [comment]
Hi @yogevyuval , looks like I found the issue. Accidentally created a bit of a race condition when attempting to prevent the "/ID" of the document from getting "decrypted". I'm nearing the end of a 3.0 release in a day or so and that will include the fix, but I'll create a patch version tomorrow to fix the issue.

Cheers!

**Comment by yogevyuval** [comment]
> Hi @yogevyuval , looks like I found the issue. Accidentally created a bit of a race condition when attempting to prevent the "/ID" of the document from getting "decrypted". I'm nearing the end of a 3.0 release in a day or so and that will include the fix, but I'll create a patch version tomorrow to fix the issue.
> 
> Cheers!

@digitalsleuth Did you have the chance to fix the issue you managed to find?

**Comment by digitalsleuth** [comment]
I did, but haven't pushed the release yet. I'm building two right now: 2.3 which will contain the fix for that, and 3.0 which will have some major upgrades (including that fix). They should be ready in the next 6 hours.

**Comment by digitalsleuth** [comment]
Hi @yogevyuval , v2.3 has been released now which fixes this issue. v3.0 will be published shortly. Let me know if this works for you.

Cheers!

**Comment by yogevyuval** [comment]
> Hi @yogevyuval , v2.3 has been released now which fixes this issue. v3.0 will be published shortly. Let me know if this works for you.
> 
> Cheers!

@digitalsleuth version 2.3.0 fixes all the issues - looks good!
Thanks!

**Comment by digitalsleuth** [comment]
@yogevyuval Glad to hear it!
