### ISSUE TITLE
Consider putting pylibemu as an optional dependency

### ISSUE THREAD

**Issue by yogevyuval** [digitalsleuth/peepdf-3#9]
Hi @digitalsleuth !

Before moving to this version of peepdf, we were using the original one which was not packaged correctly etc'. However, one regression that we are experiencing is that pylibemu is hard to install, since it requires libemu to be present in the system which can be challenging sometimes, and means that you cannot "just" pip install peepdf-3 on a brand new docker.

I think it would be very beneficial to somehow allow installing peepdf-3 without installing pylibemu, so it would be optional. It would make the installation so much more easy.

WDYT?

**Comment by yogevyuval** [comment]
> Hi @yogevyuval , that's already been added to the v3 release coming today. It will no longer come with pylibemu, but the features will still be available should the user want to install libemu and pylibemu. Thanks for mentioning it!

Fantastic, you are one step ahead already :) Waiting for the v3 release then

**Comment by digitalsleuth** [comment]
@yogevyuval Just as an FYI, I just dropped the latest version, 3.0.1 (was 3.0.0 until I noticed an error and quickly patched it). This no longer requires pylibemu.

Cheers!
